"""Initial migration - all tables

Revision ID: bf1e532df22f
Revises: 
Create Date: 2026-01-04 17:31:05.723003

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = 'bf1e532df22f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if we're using SQLite (requires batch operations)
    bind = op.get_bind()
    is_sqlite = bind.dialect.name == 'sqlite'
    
    # For SQLite, some operations need special handling
    if is_sqlite:
        # SQLite doesn't support many ALTER TABLE operations
        # We'll skip some changes that aren't critical for SQLite
        # The main goal is to ensure PostgreSQL compatibility
        with op.batch_alter_table('accounts', schema=None) as batch_op:
            batch_op.alter_column('balance',
                       existing_type=sa.FLOAT(),
                       type_=sa.Numeric(precision=10, scale=2),
                       existing_nullable=False)
    else:
        # PostgreSQL - full support
        op.alter_column('accounts', 'email_verified',
                   existing_type=sa.BOOLEAN(),
                   server_default=None,
                   existing_nullable=False)
    op.alter_column('accounts', 'balance',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('accounts', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('accounts', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('api_keys', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('api_keys', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    # Drop existing foreign key if it exists (SQLite doesn't support named constraints)
    # For SQLite, we'll recreate the table if needed, but for now just ensure the FK exists
    try:
        op.drop_constraint('api_keys_account_id_fkey', 'api_keys', type_='foreignkey')
    except:
        pass  # Constraint might not exist or have a different name
    op.create_foreign_key('api_keys_account_id_fkey', 'api_keys', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.alter_column('models', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('models', 'base_input_price',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=False)
    op.alter_column('models', 'base_output_price',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=False)
    op.alter_column('models', 'markup_percent',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('models', 'beaver_ai_input_price',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('models', 'beaver_ai_output_price',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('models', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('models', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('refresh_tokens', 'token',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'is_revoked',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    try:
        op.drop_constraint('refresh_tokens_account_id_fkey', 'refresh_tokens', type_='foreignkey')
    except:
        pass
    op.create_foreign_key('refresh_tokens_account_id_fkey', 'refresh_tokens', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.alter_column('transactions', 'amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('transactions', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('transactions', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    try:
        op.drop_constraint('transactions_account_id_fkey', 'transactions', type_='foreignkey')
    except:
        pass
    op.create_foreign_key('transactions_account_id_fkey', 'transactions', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.alter_column('usage_logs', 'total_cost',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('usage_logs', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usage_logs', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('usage_logs', 'total_cost',
               existing_type=sa.Numeric(precision=10, scale=6),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.drop_constraint('transactions_account_id_fkey', 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'accounts', ['account_id'], ['id'])
    op.alter_column('transactions', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('transactions', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('transactions', 'amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.drop_constraint('refresh_tokens_account_id_fkey', 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'refresh_tokens', 'accounts', ['account_id'], ['id'])
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=False)
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('refresh_tokens', 'is_revoked',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'token',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('models', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('models', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('models', 'beaver_ai_output_price',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.alter_column('models', 'beaver_ai_input_price',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.alter_column('models', 'markup_percent',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.alter_column('models', 'base_output_price',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('models', 'base_input_price',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('models', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('api_keys_account_id_fkey', 'api_keys', type_='foreignkey')
    op.create_foreign_key(None, 'api_keys', 'accounts', ['account_id'], ['id'])
    op.alter_column('api_keys', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('api_keys', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('accounts', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('accounts', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('accounts', 'balance',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('accounts', 'email_verified',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('0'),
               existing_nullable=False)
    # ### end Alembic commands ###

